// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLPRUivgBTRk9HNn3pDD5W8WS0UrUYWQo',
    appId: '1:652303103777:web:2319c6edafb617642b7060',
    messagingSenderId: '652303103777',
    projectId: 'benri-48d4c',
    authDomain: 'benri-48d4c.firebaseapp.com',
    storageBucket: 'benri-48d4c.firebasestorage.app',
    measurementId: 'G-X3MWLNLZYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPF3Uxykq0kFjeyR5pYOOK_ixsft664fA',
    appId: '1:652303103777:android:ae1cfe4f8afb0e092b7060',
    messagingSenderId: '652303103777',
    projectId: 'benri-48d4c',
    storageBucket: 'benri-48d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vxiTkCbQuVchI7il7CUPxnObZtpGMf8',
    appId: '1:652303103777:ios:ff0dad457cfe452f2b7060',
    messagingSenderId: '652303103777',
    projectId: 'benri-48d4c',
    storageBucket: 'benri-48d4c.firebasestorage.app',
    iosBundleId: 'com.example.benriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1vxiTkCbQuVchI7il7CUPxnObZtpGMf8',
    appId: '1:652303103777:ios:ff0dad457cfe452f2b7060',
    messagingSenderId: '652303103777',
    projectId: 'benri-48d4c',
    storageBucket: 'benri-48d4c.firebasestorage.app',
    iosBundleId: 'com.example.benriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLPRUivgBTRk9HNn3pDD5W8WS0UrUYWQo',
    appId: '1:652303103777:web:1fca16201f9212542b7060',
    messagingSenderId: '652303103777',
    projectId: 'benri-48d4c',
    authDomain: 'benri-48d4c.firebaseapp.com',
    storageBucket: 'benri-48d4c.firebasestorage.app',
    measurementId: 'G-NRFR3NNGT0',
  );
}
